title: Lukas Lee - CV
description: Estudiante de Ingeniería en Redes • Buscando Práctica Profesional
url: https://skoll43.github.io/portfolio
baseurl: ""

# GitHub Pages optimized settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# Site settings
author:
  name: Lukas Lee
  email: avgmss6qu@mozmail.com
  github: skoll43
  linkedin: lukas-lee
  credly: https://www.credly.com/users/lukaslee/badges

# GitHub Pages supported plugins are automatically enabled
sass:
  style: compressed

exclude:
  - node_modules
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
